name: Compress Images
# https://safnaj.medium.com/image-compression-for-the-web-using-github-actions-f1156d281cda
# https://github.com/marketplace/actions/image-actions

on:
  workflow_dispatch:
  
jobs:
  image_compress:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions: 
      contents: write
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: MarketingPipeline/Image-Optimizer-Action@main

      - name: Commit and push optimized images
        run: |
           git config --global user.name "github actions"
           git config --global user.email "email@gmail.com"
           git add -A
           git commit -m "Added Optimized Image"
           git push
