name: Build LaTeX document and Release PDF
  # Controls when the action will run.
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
  # https://mrturkmen.com/posts/build-release-latex/
on:
  push:
    workflow_dispatch:
       # parameters passed to this workflow through the API call
       inputs:
         # the name of the .tex file to be compiled is one of the parameters. To pass the parameters
         # in the call, here's an example curl:
         # curl -X POST -H "Accept: application/vnd/github.v3+json" 
         #   -H "authorization: Bearer <token>" https://api.github.com/repos/{owner}/{repo}/dispatches 
         #       -d '{"ref":"ref"}
         maintex:
           description: "The .tex file to be compiled"
           required: true
           type: "string"
           default: "main"
    branches: 
      - main
    paths:
      - ${{ inputs.maintex }}.tex
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:        
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          # use a Personal Access Token so that workflow can be run on private repos and
          # so that this workflow can be used in other repos
          # https://stackoverflow.com/questions/64076798/
          #     how-to-trigger-a-github-actions-workflow-on-push-to-another-branch
          # https://dev.to/dessygil/how-to-automatically-update-resume-on-your-personal-site-from-overleaf-1fld
          token: ${{ secrets.PAT }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.1.0
        with:
          root_file: ${{ inputs.maintex }}.tex
          continue_on_error: true 
      - name: Uploading artifact
        uses: actions/upload-artifact@v3
        with: 
          name: PDF
          path: ${{ inputs.maintex }}.pdf
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with: 
          timeZone: 0
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: Document compiled on ${{ steps.time.outputs.time }}
          tag_name: ${{ steps.time.outputs.time }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ inputs.maintex }}.pdf
          asset_name: ${{ inputs.maintex }}.pdf
          asset_content_type: application/pdf

