name: Build LaTeX document and Release PDF
  # Controls when the action will run.
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
  # https://mrturkmen.com/posts/build-release-latex/
on:
  push:
    branches: 
      - main
    paths:
      - main.tex
jobs:
  # followed: https://dev.to/dessygil/
  #   how-to-automatically-update-resume-on-your-personal-site-from-overleaf-1fld
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:        
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@3.1.0
        with:
          root_file: main.tex
          continue_on_error: true 
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with: 
          name: PDF
          path: main.pdf
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v2.0
        with: 
          timeZone: 0
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Publish PDF to repo
        id: create_release
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          file_pattern: '*.pdf'
          commit_message: 'Changed files'

