name: teatime Build LaTeX document and Release PDF
# Version: 07142024
#
# Is executed at gooTeX script's prompt. 
# ############################
#      Pamela M. Marcum      #
#  first created: 07/14/2024 #
# ############################
# Controls when the action will run.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://mrturkmen.com/posts/build-release-latex/
# https://github.com/PHPirates/travis-ci-latex-pdf/blob/master/.github/workflows/texlive.yml
# https://github.com/teatimeguest/setup-texlive-action  includes caching

on:
  workflow_dispatch:
    inputs: 
      file2compile:
         description: "Name of .tex file to compile, without the .tex part"
         required: true
         default: "main"        
         
jobs:
  build_latex:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
      
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
       
      - name: Install texlive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages:
            scheme-basic
            collection-mathscience
            collection-bibtexextra
            collection-fontutils
          cache: true
            
      - name: Compile paper
        run: |
          latexmk -bibtex -f -g -pdf -time -file-line-error -view=none  -interaction=nonstopmode ${{ github.event.inputs.file2compile }}
        continue-on-error: true
     
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with: 
          name: PDF
          path: "${{ github.event.inputs.file2compile }}.pdf"
        continue-on-error: true
         
      - name: Publish PDF to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '${{ github.event.inputs.file2compile }}.pdf'
          commit_message: 'Newly compiled PDF'
        continue-on-error: true

